name: multimodal-emotion-detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - cudatoolkit=11.1
  - matplotlib=3.3.2
  - scikit-learn
  - seaborn
  - pandas
  - numpy
  - pytorch
  - torchaudio
  - notebook=6.3.0
  - pip=20.2.4
  - pip:
    - wandb
    - tqdm
    - dvc
    - librosa